### ISSUE TITLE
Getting FatalErrorException for max. function nesting level on admin page

### ISSUE THREAD

**Issue by PatricB** [SleepingOwlAdmin/demo#13]
Hey,

I installed the demo on my local system. The home page works finde, but when try to access the admin page I get following error:
**FatalErrorException in Container.php line 698:
Maximum function nesting level of '100' reached, aborting!**

Have I maybe missed something to  configure? It seems not to happen if I have only navigation items without pages (only url).

Beste regards

**Comment by Big-Shark** [comment]
@PatricB The current version https://github.com/LaravelRUS/SleepingOwlAdmin

**Comment by PatricB** [comment]
@Big-Shark But this demo require the dev-development version of laravelrus/sleepingowl ...

```
        ...
        "laravel/framework": "5.2.*",
        "laravelrus/sleepingowl": "dev-development",
       ...
```
[demo/composer.json](https://github.com/SleepingOwlAdmin/demo/blob/master/composer.json)

**Comment by PatricB** [comment]
ah ok. Fault of mine. My Xdebug give the max. function nesting level of '100'. Raised it up and now it works!

Bug can be closed.
