### ISSUE TITLE
I can access admin dashboard directly without login.  

### ISSUE THREAD

**Issue by waqasmehmud** [SleepingOwlAdmin/demo#14]
I need to restrict admin area by login.

**Comment by butschster** [comment]
You can change default guard to admin or change middleware in config/sleeping_owl.php to

'middleware' => ['web', 'auth:admin'],

**Comment by waqasmehmud** [comment]
sleeping_owl.php this file does not exists here https://github.com/SleepingOwlAdmin/demo/tree/master/config

**Comment by waqasmehmud** [comment]
even on demo link i can access admin area without login http://demo.sleepingowladmin.ru/admin

**Comment by butschster** [comment]
`php artisan sleepingowl:install`
https://github.com/LaravelRUS/SleepingOwlAdmin#authentication

**Comment by waqasmehmud** [comment]
I followed all the steps, admin link now redirects to frontend login and after login it redirects to frontend home page not admin dashboard

**Comment by butschster** [comment]
You should run artisan command `php artisan sleepingowl:install`
And then you should open `config/sleeping_owl.php` and append middleware `auth:admin`

```php
// before
'middleware' => ['web'],

// after
'middleware' => ['web', 'auth:admin'],
```

**Comment by waqasmehmud** [comment]
yes, did exactly same as you said. tried with new installation as well. but results still same. it redirects to default laravel auth login and after login to home page. i can't access dashboard.

**Comment by SCIF** [comment]
@butschster , @waqasmehmud not `auth:admin` — just `auth` for default installation of demo app. I.e., `slepping_owl.php`
```
    'middleware' => ['web', 'auth'],
```

@butschster , what do you think to add it as default to demo application? It seems expectable if you install demo app.
