### ISSUE TITLE
Не работает фильтр setColumnFilters для table()

### ISSUE THREAD

**Issue by dronowar** [SleepingOwlAdmin/demo#30]
В демо версии на странице
https://demo.sleepingowladmin.ru/admin/contact4s
не работает фильтр по столбцам, нажатие кнопки Filter не приводит к отправке формы или ajax запросу.

**Comment by mavsan** [comment]
Все еще не работает.

**Comment by mavsan** [comment]
Изучение кода js админки выявило, что событие `click` на элемент `#filters-exec` (кнопка фильтра) вешается только для `datatables`. В инструкции об этом не сказано (что фильтр работает только с datatables).
Т.е. в начале надо загрузить туда все 100500 записей, и уже потом искать. Видимо для этого начали делать `datatablesAsync`.

**Comment by aios** [comment]
@mavsan собственно filters-exec кнопка была придумана как раз для большого количества данных - а по скольку datatables то количество данных, которое есть в больших компаниях то кнопка и сами фильтры были больше переработаны как раз для Async. В чем я сомневаюсь так это в работе остальных Display типо table и datatables.

**Comment by aios** [comment]
Блин....
@dronowar @mavsan там позиция элементов фильтра находится в футере - надо ишью поправить слегка и добавить в главный репо - фильтры срабатывают только сверху таблицы) не знаю - но догадываюсь почему так происходит - так что пофикшу)

**Comment by Argentum88** [comment]
Все еще не работает. (((

**Comment by mavsan** [comment]
@Argentum88 работает (хотя и глючит) для `datatablesAsync`, а в демо вроде бы `table`. Во всяком случае у меня для `datatablesAsync` работает (хотя и глючит не много).

**Comment by Argentum88** [comment]
Это да, но меня прям разрывает от желания, что-бы они работали именно в `table`.
