### ISSUE TITLE
Как сделать?

### ISSUE THREAD

**Issue by eskrano** [SleepingOwlAdmin/demo#33]
Подскажите как сделать что когда например редактируется продукт то я мог также добавлять опции т.е связанные опции и тд. Есть модель Product и модель ProductAttribute разумеется с Product идет связь один ко многим к ProductAttribute, вот я хочу редактировать эти аттрибуты когда редачу продукт. Подскажите как решить данный вопрос?

**Comment by Lunatig** [comment]
задайте ваш вопрос в чате пожалуйста. 
тут пишем если что-то не работает в демке или запросы на добавление. 

один из вариантов решения вопроса в демке реализован тут во второй и третьей вкладке
 https://demo.sleepingowladmin.ru/admin/contact5s
