### ISSUE TITLE
Кнопка Save and create 

### ISSUE THREAD

**Issue by mavsan** [SleepingOwlAdmin/demo#34]
Создаю запись для https://demo.sleepingowladmin.ru/admin/pages:
Title: `Тестовая запись`
Text: `Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись Тестовая запись `

При создании записи все отрабатывает хорошо, и записывается. Изменяется тоже все отлично. Но если нажать на кнопку `Save and create` появляется ошибка:

![image](https://cloud.githubusercontent.com/assets/5114650/25460590/c0db904c-2b27-11e7-9d96-00138f5d321c.png)

**Comment by mavsan** [comment]
На всякий случай напомню про не баг, бажище.

**Comment by aios** [comment]
Видимо не везде переопределил. Хотя должно работать во всей админке.
