### ISSUE TITLE
нерабочий docker-compose up

### ISSUE THREAD

**Issue by magnum-ferox** [SleepingOwlAdmin/demo#42]
сразу отваливается один контейнер
soa_data exited with code 0

при попытке открыть сайт:

soa_caddy | 04/Nov/2017:16:31:06 +0000 [ERROR 0 /] PHP message: PHP Warning:  require(/app/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /app/bootstrap/autoload.php on line 17
soa_caddy | PHP message: PHP Stack trace:
soa_caddy | PHP message: PHP   1. {main}() /app/public/index.php:0
soa_caddy | PHP message: PHP   2. require() /app/public/index.php:22
soa_caddy | PHP message: PHP Fatal error:  require(): Failed opening required '/app/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/bootstrap/autoload.php on line 17
soa_caddy | PHP message: PHP Stack trace:
soa_caddy | PHP message: PHP   1. {main}() /app/public/index.php:0
soa_caddy | PHP message: PHP   2. require() /app/public/index.php:22

**Comment by aios** [comment]
`docker-compose exec -ti sleepingowl_app_1 /bin/bash
composer update
php artisan migrate:fresh --seed`
