### ISSUE TITLE
Ckeditor not working?

### ISSUE THREAD

**Issue by s6carlo** [SleepingOwlAdmin/demo#6]
Is ckeditor working? In "Form Items" page I have a simple textarea and not ckeditor .

If it is working it is possibie to add plugins? In the sleeping-owl/admin project I had the problem for the image browser feature: it uses a plugin which show the image list without the file name and it is not easy to use when there are a lot of files in the image upload directory.

Carlo

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.21.94-beta
https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.22.96-beta
